### ISSUE TITLE
SPC doesnt not process <script> tag

### ISSUE THREAD

**Issue by viktor-mozz** [denivip/jquery-openxtag#3] opened 2012-02-22 22:05 UTC
Hi, 

I was checking the SPC response and i have some video ad and external banner (like doubleclick). These banners cannot work right because the plugin cut out the "script tag" part from the response of the SPC-Call so i have to change the "script tag" call for "iframe tag" call in the external banners , but what happend with the banners that use "script tag" like video ads?  

can you give a light in the issue? or maybe i'm doing something wrong with this plugin ... U_U

**Comment by huangzj** [comment] 2012-03-18 07:03
I'm facing the same problem too. :( Looks like it's related to how function (markup) within _documentWriteSafeAppend is handling the response from the ad server. On the second loop when the server returns data formatted similar to data from a jsZone:

`var OX_44c3825a = '';
OX_44c3825a += "<"+"a href=\'__URL__\' /><"+"/a><"+"img src=\'__SRC__\' />\n";
document.write(OX_44c3825a);`

It fails because this wasn't wrapped in the format

`'<script type="text/javascript">' + data + '</script>'`

Perhaps this is helpful in fixing the problem?

**Comment by jimpo** [comment] 2012-08-23 22:50
It seems to be a race condition in _documentWriteSafeAppend(). document.write (called from the loaded script) is executed after the _documentWriteSafeAppend() finishes and document.write is reset to the original value, so buffer is never populated.

**Comment by Crazy-Achmet** [comment] 2013-01-28 13:04
It would be great if you could fix this bug! ;) I'm also willing to make a donation to you for this awesome plugin. ;) Just give me your paypal address if you're interested.

**Comment by Crazy-Achmet** [comment] 2013-09-12 12:15
I'm still interested in paying someone who is fixing this problem! PLEASE! ;)

**Comment by Patricy** [comment] 2013-09-17 15:44
i making fix for this.

Can somebody check my fix on own projects?
in _documentWriteSafeAppend()

``` javascript
document.write = function (markup) {
    buffer += markup;
};
//FIX                
//getting external scripts and after - appending server response
var matchesScripts = markup.match(/<script.*?src ?= ?"([^"]+)"/);
if (matchesScripts && typeof matchesScripts[1] != 'undefined'){
$.getScript(matchesScripts[1], function() {                 
    $this.append(markup);
});
} else {
    $this.append(markup);
}
//END OF FIX         
document.write = oldDocumentWrite;
```

**Comment by Crazy-Achmet** [comment] 2013-09-18 07:31
It doesn't work on my project. The script part still doesn't show up. :-/

**Comment by Patricy** [comment] 2013-09-18 08:30
Please, can you show me the page (url) where its not working? I tested it on local openx server and I can check it on working envirement.

**Comment by Crazy-Achmet** [comment] 2013-09-18 09:08
Sure, there you go: http://www.planet-liebe.de/temp/openx-test/examples/spc-with-metadata.html

One banner (the local one) is displayed, the other won't show up

**Comment by Crazy-Achmet** [comment] 2013-09-19 09:27
Do you have any idea, why that happens? Or do you need more information about the Banner?

**Comment by Crazy-Achmet** [comment] 2013-09-19 09:54
What do you mean by iframe tag. I don't think i use that method (but i'm not sure either).

 

Let me know if you need more information about the original code (how the banner code with openx and without openx looks).

 

Thank you so much for your help!

 

Gesendet: Donnerstag, 19. September 2013 um 11:32 UhrVon: Patricy notifications@github.comAn: denivip/jquery-openxtag jquery-openxtag@noreply.github.comCc: Flo florian-2k@gmx.deBetreff: Re: [jquery-openxtag] SPC doesnt not process <script> tag (#3)

Yes, I have. My fix was about ))
I changed the way of including remote js.

But you use iframe tag. It also can not be easy appended via js.
It needs to use similar ways, via creating DOM element, i think.

I will try to do another fix for this.

**Comment by Patricy** [comment] 2013-09-19 14:28
i have some questions but can we use email to discuss this things?  
my: 777@patricy.com.ua

**Comment by Patricy** [comment] 2013-09-19 18:53
can you provide maximum information about openX banner settings?
urls, settings, etc

**Comment by Crazy-Achmet** [comment] 2013-10-15 09:46
Any news on this?

**Comment by Patricy** [comment] 2013-10-15 09:49
Hi

I had a look on it and still cannot repeat this bug on my local machine.

Can you provide more data:
all urls, created campaigns, banners (types, urls), etc which u use in
openX server.

I need exactly same data to repeat it.

Thanks

2013/10/15 Flo notifications@github.com

> Any news on this?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/denivip/jquery-openxtag/issues/3#issuecomment-26321586
> .

## 

ó Õ×ÁÖÅÎÉÅÍ,
ëÉÃÀË óÅÒÇÅÊ

+420 774 174 987

**Comment by Crazy-Achmet** [comment] 2013-10-15 10:09
I've sended you a mail with account data to my OpenX System.

**Comment by Crazy-Achmet** [comment] 2013-10-15 21:16
Did you got it and did it help?

**Comment by dangerden** [comment] 2013-10-23 05:28
Hi @Crazy-Achmet 

We have reviewed your case. It took quite a lot of time. And our understanding of the problem is following.

First of all there is no any zones related issues.

Our developers downloaded your getads.js script and debugged it in Chrome.

The root cause of the problem is that after GlamShow() function call there is a sequence of DOM insertions of <script src> in a recursion. At some point of time those insertions start to happen asynchonously related to our plug in, that's why document.write overriding doesn't work.

There is a workaround for that to load the plug in using ajax and insert it into <script></script> the corresponding div element. But ajax is available only for the same domain.

It doesn't seem that we could do anything on this issue at the moment.

Thank you,
Denis.

**Closed as completed by dangerden** 2013-10-23 05:28 UTC
